name: Gerar inputs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Gerar_inputs_aleatorios:
    run:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: instalar o py
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'  
      
      - name: Instalar pillow e atualizar
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
      
      - name: Executar o programa
        run: cd src/
        run: python3 app.py

      - name: Faça o upload dos resultados dos testes
            uses: actions/upload-artifact@v4
            if: always()
            with:
              name: Resultado dos testes
              path: src/results/

